# Generated by Django 4.2.11 on 2025-06-12 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EspeciesSonidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabacionSonido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('archivo_audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('especie_sonido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EspeciesSonidos.especiesonido')),
            ],
        ),
    ]
