# Generated by Django 4.2.11 on 2025-06-12 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Especies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieSonido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sonido', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('pdf_estudio', models.FileField(blank=True, null=True, upload_to='pdf_estudios/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especies.especie')),
            ],
        ),
    ]
