# Generated by Django 4.2.11 on 2025-06-12 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GrabacionSonidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSonido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investigador', models.CharField(max_length=100)),
                ('fecha_analisis', models.DateField()),
                ('observaciones', models.TextField()),
                ('pdf_resultados', models.FileField(blank=True, null=True, upload_to='resultados_pdf/')),
                ('grabacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrabacionSonidos.grabacionsonido')),
            ],
        ),
    ]
